[package]
name = "volta-layout-macro"
version = "0.1.0"
authors = ["David Herman <david.herman@gmail.com>"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "=1.0.109"
quote = "1.0.41"
proc-macro2 = "1.0.103"
